#!/usr/bin/env bash

if ! dpkg -s clang >/dev/null 2>&1; then
  echo -e "[ERROR] Clang is not installed\n[NOTE] Please run apt-get install clang"
fi

echo -e "[NOTE] Compiling server.cpp"
server=$(g++ server.cpp -o server -lpthread)
if [[ $? != 0 ]]; then
    echo -e "[ERROR] : $(server)"
else
    echo -e "[NOTE] Compiled server.cpp into server"
fi

echo "[NOTE] Compiling client.cpp"
client=$(g++ client.cpp -o client)
if [[ $? != 0 ]]; then
    echo "[ERROR] : $(client)"
else
    echo "[NOTE] Compiled client.cpp into client"
fi